const APP_VERSION="2.0.0";const STORAGE_KEY="finance_tracker_v2";const OLD_STORAGE_KEY="finance_tracker_v1";const AUTH_KEY="finance_tracker_auth_v2";const OLD_AUTH_KEY="finance_tracker_auth_v1";
const mkid=()=>crypto.randomUUID();
const defaultState={version:APP_VERSION,income:2700,expenses:[['Rent',650],['Council Tax',178],['Phone',104],['Broadband',25],['Life Insurance',45],['Fuel',200],['Disney',6],['OpenAI',20],['Google',5],['Amazon',9],['Tithe',270],['Offerings',80],['Family Support',100],['ALC9 Payment',200],['Klarna Payment',118],['HSBC Overdraft',445]].map(([name,amount])=>({id:mkid(),name,amount,paid:false,recurring:true})),debts:[{id:mkid(),name:'ALC9',balance:12000,payment:200,apr:0},{id:mkid(),name:'Klarna',balance:232,payment:118,apr:0},{id:mkid(),name:'HSBC Overdraft',balance:445,payment:445,apr:39.9}],history:[]};
let state=loadState(),expenseChart=null,debtChart=null,unlocked=false,chartRenderTimer=null,deferredInstallPrompt=null;
function migrateAuth(){const n=localStorage.getItem(AUTH_KEY),o=localStorage.getItem(OLD_AUTH_KEY);if(!n&&o)localStorage.setItem(AUTH_KEY,o)}
function migrateState(raw){const m=raw||structuredClone(defaultState);m.version=APP_VERSION;m.income=Number(m.income||0);m.expenses=Array.isArray(m.expenses)?m.expenses:[];m.debts=Array.isArray(m.debts)?m.debts:[];m.history=Array.isArray(m.history)?m.history:[];m.expenses=m.expenses.map(i=>({id:i.id||mkid(),name:i.name||'Unnamed Expense',amount:Number(i.amount||0),paid:Boolean(i.paid),recurring:i.recurring!==false}));m.debts=m.debts.map(d=>({id:d.id||mkid(),name:d.name||'Unnamed Debt',balance:Number(d.balance||0),payment:Number(d.payment||0),apr:Number(d.apr||0)}));return m}
function loadState(){const s=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(OLD_STORAGE_KEY);if(!s)return structuredClone(defaultState);try{return migrateState(JSON.parse(s))}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
async function sha256(t){const d=new TextEncoder().encode(t),b=await crypto.subtle.digest('SHA-256',d);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function getAuth(){const r=localStorage.getItem(AUTH_KEY);return r?JSON.parse(r):null}function setAuth(a){localStorage.setItem(AUTH_KEY,JSON.stringify(a))}
function clearAuthInputs(){passwordInput.value='';confirmPasswordInput.value=''}
function showAuthMode(){const a=getAuth(),setup=!a;authScreen.classList.remove('hidden');mainApp.classList.add('hidden');authTitle.textContent=setup?'Set Password':'Enter Password / PIN';authSubtitle.textContent=setup?'Create a password for this device.':'Unlock your finance tracker.';authButton.textContent=setup?'Save Password':'Unlock';confirmPasswordInput.classList.toggle('hidden',!setup);forgotPasswordBtn.classList.toggle('hidden',setup);authMessage.textContent='';clearAuthInputs()}
function unlockApp(){unlocked=true;authScreen.classList.add('hidden');mainApp.classList.remove('hidden');render()}
authForm.addEventListener('submit',async e=>{e.preventDefault();const a=getAuth(),p=passwordInput.value,c=confirmPasswordInput.value;if(!a){if(p.length<4){authMessage.textContent='Use at least 4 characters.';return}if(p!==c){authMessage.textContent='Passwords do not match.';return}const salt=mkid(),hash=await sha256(salt+p);setAuth({salt,hash,hasPin:false,pinSalt:null,pinHash:null});unlockApp();return}const ph=await sha256(a.salt+p);const pinh=a.hasPin&&a.pinSalt?await sha256(a.pinSalt+p):null;if(ph===a.hash||pinh===a.pinHash)unlockApp();else authMessage.textContent='Incorrect password or PIN.'});
forgotPasswordBtn.addEventListener('click',()=>{if(!confirm("Password reset will delete this device's saved finance data and password. Continue?"))return;localStorage.removeItem(AUTH_KEY);localStorage.removeItem(STORAGE_KEY);state=structuredClone(defaultState);showAuthMode()});lockBtn.addEventListener('click',()=>{unlocked=false;showAuthMode()});
changePasswordBtn.addEventListener('click',async()=>{const a=getAuth();if(!a)return;const cur=prompt('Enter current password:');if(cur===null)return;if(await sha256(a.salt+cur)!==a.hash){alert('Incorrect current password.');return}const np=prompt('Enter new password:');if(np===null)return;if(np.length<4){alert('Use at least 4 characters.');return}const cp=prompt('Confirm new password:');if(cp===null)return;if(np!==cp){alert('Passwords do not match.');return}const salt=mkid(),hash=await sha256(salt+np);setAuth({...a,salt,hash});alert('Password changed.')});
setPinBtn.addEventListener('click',async()=>{const a=getAuth();if(!a)return;const cur=prompt('Enter main password first:');if(cur===null)return;if(await sha256(a.salt+cur)!==a.hash){alert('Incorrect password.');return}const pin=prompt('Enter a 4-digit quick PIN:');if(pin===null)return;if(!/^\d{4}$/.test(pin)){alert('PIN must be exactly 4 digits.');return}const cp=prompt('Confirm PIN:');if(cp===null)return;if(pin!==cp){alert('PINs do not match.');return}const pinSalt=mkid(),pinHash=await sha256(pinSalt+pin);setAuth({...a,hasPin:true,pinSalt,pinHash});alert('Quick PIN set.')});
removePinBtn.addEventListener('click',async()=>{const a=getAuth();if(!a||!a.hasPin){alert('No PIN is currently set.');return}const cur=prompt('Enter main password to remove PIN:');if(cur===null)return;if(await sha256(a.salt+cur)!==a.hash){alert('Incorrect password.');return}setAuth({...a,hasPin:false,pinSalt:null,pinHash:null});alert('Quick PIN removed.')});
function money(v){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(v||0))}function totalExpenses(){return state.expenses.reduce((s,i)=>s+Number(i.amount||0),0)}function paidThisMonth(){return state.expenses.filter(i=>i.paid).reduce((s,i)=>s+Number(i.amount||0),0)}function remainingToPay(){return state.expenses.filter(i=>!i.paid).reduce((s,i)=>s+Number(i.amount||0),0)}function totalDebt(){return state.debts.reduce((s,d)=>s+Number(d.balance||0),0)}
function amortiseDebt(balance,payment,apr){balance=Number(balance||0);payment=Number(payment||0);apr=Number(apr||0);if(balance<=0)return{months:0,totalInterest:0,payoffDate:'Cleared'};if(payment<=0)return{months:'No payment',totalInterest:0,payoffDate:'N/A'};const r=apr/100/12;let m=0,ti=0,b=balance;while(b>0&&m<1200){const i=b*r;if(payment<=i&&r>0)return{months:'Not reducing',totalInterest:ti,payoffDate:'N/A'};b+=i;ti+=i;b-=payment;m++}if(m>=1200)return{months:'100+ years',totalInterest:ti,payoffDate:'N/A'};const date=new Date();date.setMonth(date.getMonth()+m);return{months:m,totalInterest:ti,payoffDate:date.toLocaleDateString('en-GB',{month:'short',year:'numeric'})}}
function renderDashboard(){const inc=Number(state.income||0),out=totalExpenses(),paid=paidThisMonth(),rem=remainingToPay(),left=inc-rem;incomeDisplay.textContent=money(inc);outgoingsDisplay.textContent=money(out);paidDisplay.textContent=money(paid);leftDisplay.textContent=money(left);leftDisplay.className=left>=0?'positive':'negative';remainingText.textContent=`Remaining to pay: ${money(rem)}`;debtTotalText.textContent=`Total debt: ${money(totalDebt())}`;incomeInput.value=state.income}
function renderExpenses(){expensesTable.innerHTML='';state.expenses.forEach(i=>{const r=document.createElement('tr');r.innerHTML=`<td><input class="checkbox" type="checkbox" ${i.paid?'checked':''} data-action="toggle-paid" data-id="${i.id}" /></td><td>${i.name}</td><td>${money(i.amount)}</td><td>${i.paid?money(0):money(i.amount)}</td><td>${i.recurring?'Yes':'No'}</td><td><button class="icon-btn edit" data-action="edit-expense" data-id="${i.id}">Edit</button><button class="icon-btn delete" data-action="delete-expense" data-id="${i.id}">Delete</button></td>`;expensesTable.appendChild(r)})}
function renderDebts(){debtsTable.innerHTML='';state.debts.forEach(d=>{const a=amortiseDebt(d.balance,d.payment,d.apr),r=document.createElement('tr');r.innerHTML=`<td>${d.name}</td><td>${money(d.balance)}</td><td>${money(d.payment)}</td><td>${Number(d.apr||0).toFixed(2)}%</td><td>${a.months}</td><td>${money(a.totalInterest)}</td><td>${a.payoffDate}</td><td><button class="icon-btn edit" data-action="edit-debt" data-id="${d.id}">Edit</button><button class="icon-btn delete" data-action="delete-debt" data-id="${d.id}">Delete</button></td>`;debtsTable.appendChild(r)})}
function renderHistory(){historyTable.innerHTML='';if(!state.history.length){historyTable.innerHTML='<tr><td colspan="7">No archived months yet.</td></tr>';return}[...state.history].reverse().forEach(h=>{const r=document.createElement('tr');r.innerHTML=`<td>${h.date}</td><td>${money(h.income)}</td><td>${money(h.totalExpenses)}</td><td>${money(h.paid)}</td><td>${money(h.remaining)}</td><td>${money(h.totalDebt)}</td><td><button class="icon-btn delete" data-action="delete-history" data-id="${h.id}">Delete</button></td>`;historyTable.appendChild(r)})}
function createOrUpdateCharts(){const el=document.getElementById('expenseChart'),dl=document.getElementById('debtChart'),labs=state.expenses.map(i=>i.name),dat=state.expenses.map(i=>Number(i.amount||0)),dlabs=state.debts.map(d=>d.name),ddat=state.debts.map(d=>Number(d.balance||0));if(!expenseChart)expenseChart=new Chart(el,{type:'doughnut',data:{labels:labs,datasets:[{label:'Expenses',data:dat}]},options:{responsive:true,maintainAspectRatio:false,resizeDelay:200,animation:false}});else{expenseChart.data.labels=labs;expenseChart.data.datasets[0].data=dat;expenseChart.update('none')}if(!debtChart)debtChart=new Chart(dl,{type:'bar',data:{labels:dlabs,datasets:[{label:'Debt Balance',data:ddat}]},options:{responsive:true,maintainAspectRatio:false,resizeDelay:200,animation:false}});else{debtChart.data.labels=dlabs;debtChart.data.datasets[0].data=ddat;debtChart.update('none')}}function scheduleChartRender(){clearTimeout(chartRenderTimer);chartRenderTimer=setTimeout(createOrUpdateCharts,50)}
function render(){if(!unlocked)return;renderDashboard();renderExpenses();renderDebts();renderHistory();scheduleChartRender();saveState()}
incomeInput.addEventListener('input',e=>{state.income=Number(e.target.value||0);render()});expenseForm.addEventListener('submit',e=>{e.preventDefault();const name=expenseName.value.trim(),amount=Number(expenseAmount.value),recurring=expenseRecurring.checked;if(!name||amount<0)return;state.expenses.push({id:mkid(),name,amount,paid:false,recurring});e.target.reset();expenseRecurring.checked=true;render()});debtForm.addEventListener('submit',e=>{e.preventDefault();const name=debtName.value.trim(),balance=Number(debtBalance.value),payment=Number(debtPayment.value),apr=Number(debtInterest.value||0);if(!name||balance<0||payment<0||apr<0)return;state.debts.push({id:mkid(),name,balance,payment,apr});e.target.reset();render()});
document.addEventListener('click',e=>{const action=e.target.dataset.action,id=e.target.dataset.id;if(!action||!id)return;if(action==='edit-expense'){const i=state.expenses.find(x=>x.id===id);if(!i)return;const name=prompt('Expense name:',i.name);if(name===null)return;const amount=prompt('Amount £:',i.amount);if(amount===null)return;const recurring=confirm('Should this be recurring every month? Press OK for Yes, Cancel for No.');i.name=name.trim()||i.name;i.amount=Number(amount||i.amount);i.recurring=recurring;render()}if(action==='delete-expense'){state.expenses=state.expenses.filter(x=>x.id!==id);render()}if(action==='edit-debt'){const d=state.debts.find(x=>x.id===id);if(!d)return;const name=prompt('Debt name:',d.name);if(name===null)return;const balance=prompt('Balance £:',d.balance);if(balance===null)return;const payment=prompt('Monthly payment £:',d.payment);if(payment===null)return;const apr=prompt('APR %:',d.apr);if(apr===null)return;d.name=name.trim()||d.name;d.balance=Number(balance||d.balance);d.payment=Number(payment||d.payment);d.apr=Number(apr||0);render()}if(action==='delete-debt'){state.debts=state.debts.filter(x=>x.id!==id);render()}if(action==='delete-history'){state.history=state.history.filter(x=>x.id!==id);render()}});
document.addEventListener('change',e=>{if(e.target.dataset.action==='toggle-paid'){const i=state.expenses.find(x=>x.id===e.target.dataset.id);if(i){i.paid=e.target.checked;render()}}});
markAllPaidBtn.addEventListener('click',()=>{state.expenses.forEach(i=>i.paid=true);render()});markAllUnpaidBtn.addEventListener('click',()=>{state.expenses.forEach(i=>i.paid=false);render()});resetMonthBtn.addEventListener('click',()=>{if(confirm('Reset all monthly paid ticks to unpaid?')){state.expenses.forEach(i=>i.paid=false);render()}});archiveMonthBtn.addEventListener('click',()=>{state.history.push({id:mkid(),date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),income:state.income,totalExpenses:totalExpenses(),paid:paidThisMonth(),remaining:remainingToPay(),totalDebt:totalDebt()});state.expenses=state.expenses.filter(i=>i.recurring).map(i=>({...i,paid:false}));render()});factoryResetBtn.addEventListener('click',()=>{if(confirm('This will restore the original budget and delete your edits/history. Continue?')){state=structuredClone(defaultState);render()}});
exportBtn.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`finance-tracker-backup-v${APP_VERSION}.json`;a.click();URL.revokeObjectURL(url)});importInput.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const imported=migrateState(JSON.parse(r.result));if(!imported.expenses||!imported.debts)throw new Error();state=imported;render()}catch{alert('Import failed. Please check the backup file.')}};r.readAsText(f)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.classList.remove('hidden')});installBtn.addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.classList.add('hidden')});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;installBtn.classList.add('hidden')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(console.error);migrateAuth();saveState();showAuthMode();
