const APP_VERSION="3.0.0";
const STORAGE_KEY="finance_monthly_money_tracker_v3";
const AUTH_KEY="finance_monthly_money_tracker_auth_v3";

const blankState={version:APP_VERSION,income:0,expenses:[],debts:[],history:[]};
const sampleState={version:APP_VERSION,income:2700,expenses:[
{id:crypto.randomUUID(),name:"Rent / Mortgage",amount:650,paid:false,recurring:true},
{id:crypto.randomUUID(),name:"Council Tax",amount:178,paid:false,recurring:true},
{id:crypto.randomUUID(),name:"Phone",amount:60,paid:false,recurring:true},
{id:crypto.randomUUID(),name:"Broadband",amount:30,paid:false,recurring:true},
{id:crypto.randomUUID(),name:"Fuel / Travel",amount:200,paid:false,recurring:true},
{id:crypto.randomUUID(),name:"Food Shopping",amount:350,paid:false,recurring:true}],debts:[
{id:crypto.randomUUID(),name:"Credit Card",balance:1000,payment:100,apr:29.9},
{id:crypto.randomUUID(),name:"Loan",balance:5000,payment:200,apr:0}],history:[]};

let state=loadState(),expenseChart=null,debtChart=null,unlocked=false,chartRenderTimer=null,deferredInstallPrompt=null;

function loadState(){const saved=localStorage.getItem(STORAGE_KEY);if(!saved)return structuredClone(blankState);try{return migrateState(JSON.parse(saved))}catch{return structuredClone(blankState)}}
function migrateState(raw){const s=raw||structuredClone(blankState);s.version=APP_VERSION;s.income=Number(s.income||0);s.expenses=Array.isArray(s.expenses)?s.expenses:[];s.debts=Array.isArray(s.debts)?s.debts:[];s.history=Array.isArray(s.history)?s.history:[];s.expenses=s.expenses.map(x=>({id:x.id||crypto.randomUUID(),name:x.name||"Unnamed Item",amount:Number(x.amount||0),paid:Boolean(x.paid),recurring:x.recurring!==false}));s.debts=s.debts.map(x=>({id:x.id||crypto.randomUUID(),name:x.name||"Unnamed Debt",balance:Number(x.balance||0),payment:Number(x.payment||0),apr:Number(x.apr||0)}));return s}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
async function sha256(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-256",data);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function getAuth(){const raw=localStorage.getItem(AUTH_KEY);return raw?JSON.parse(raw):null}
function setAuth(auth){localStorage.setItem(AUTH_KEY,JSON.stringify(auth))}
function clearAuthInputs(){passwordInput.value="";confirmPasswordInput.value=""}
function showAuthMode(){const auth=getAuth(),isSetup=!auth;authScreen.classList.remove("hidden");mainApp.classList.add("hidden");authTitle.textContent=isSetup?"Set Password":"Enter Password / PIN";authSubtitle.textContent=isSetup?"Create a password for this device.":"Unlock your money tracker.";authButton.textContent=isSetup?"Save Password":"Unlock";confirmPasswordInput.classList.toggle("hidden",!isSetup);forgotPasswordBtn.classList.toggle("hidden",isSetup);authMessage.textContent="";clearAuthInputs()}
function unlockApp(){unlocked=true;authScreen.classList.add("hidden");mainApp.classList.remove("hidden");render()}

authForm.addEventListener("submit",async e=>{e.preventDefault();const auth=getAuth(),password=passwordInput.value,confirmPassword=confirmPasswordInput.value;if(!auth){if(password.length<4){authMessage.textContent="Use at least 4 characters.";return}if(password!==confirmPassword){authMessage.textContent="Passwords do not match.";return}const salt=crypto.randomUUID(),hash=await sha256(salt+password);setAuth({salt,hash,hasPin:false,pinSalt:null,pinHash:null});unlockApp();return}const passwordHash=await sha256(auth.salt+password);const pinHash=auth.hasPin&&auth.pinSalt?await sha256(auth.pinSalt+password):null;if(passwordHash===auth.hash||pinHash===auth.pinHash)unlockApp();else authMessage.textContent="Incorrect password or PIN."});
forgotPasswordBtn.addEventListener("click",()=>{if(!confirm("Password reset will delete this device's saved finance data and password. Continue?"))return;localStorage.removeItem(AUTH_KEY);localStorage.removeItem(STORAGE_KEY);state=structuredClone(blankState);showAuthMode()});
lockBtn.addEventListener("click",()=>{unlocked=false;showAuthMode()});
changePasswordBtn.addEventListener("click",async()=>{const auth=getAuth();if(!auth)return;const current=prompt("Enter current password:");if(current===null)return;if(await sha256(auth.salt+current)!==auth.hash){alert("Incorrect current password.");return}const next=prompt("Enter new password:");if(next===null)return;if(next.length<4){alert("Use at least 4 characters.");return}const confirmNext=prompt("Confirm new password:");if(confirmNext!==next){alert("Passwords do not match.");return}const salt=crypto.randomUUID(),hash=await sha256(salt+next);setAuth({...auth,salt,hash});alert("Password changed.")});
setPinBtn.addEventListener("click",async()=>{const auth=getAuth();if(!auth)return;const current=prompt("Enter main password first:");if(current===null)return;if(await sha256(auth.salt+current)!==auth.hash){alert("Incorrect password.");return}const pin=prompt("Enter a 4-digit quick PIN:");if(pin===null)return;if(!/^\d{4}$/.test(pin)){alert("PIN must be exactly 4 digits.");return}const pin2=prompt("Confirm PIN:");if(pin!==pin2){alert("PINs do not match.");return}const pinSalt=crypto.randomUUID(),pinHash=await sha256(pinSalt+pin);setAuth({...auth,hasPin:true,pinSalt,pinHash});alert("Quick PIN set.")});
removePinBtn.addEventListener("click",async()=>{const auth=getAuth();if(!auth||!auth.hasPin){alert("No PIN is currently set.");return}const current=prompt("Enter main password to remove PIN:");if(current===null)return;if(await sha256(auth.salt+current)!==auth.hash){alert("Incorrect password.");return}setAuth({...auth,hasPin:false,pinSalt:null,pinHash:null});alert("Quick PIN removed.")});

function money(v){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(v||0))}
function totalExpenses(){return state.expenses.reduce((s,x)=>s+Number(x.amount||0),0)}
function paidThisMonth(){return state.expenses.filter(x=>x.paid).reduce((s,x)=>s+Number(x.amount||0),0)}
function remainingToPay(){return state.expenses.filter(x=>!x.paid).reduce((s,x)=>s+Number(x.amount||0),0)}
function totalDebt(){return state.debts.reduce((s,x)=>s+Number(x.balance||0),0)}
function amortiseDebt(balance,payment,apr){balance=Number(balance||0);payment=Number(payment||0);apr=Number(apr||0);if(balance<=0)return{months:0,totalInterest:0,payoffDate:"Cleared"};if(payment<=0)return{months:"No payment",totalInterest:0,payoffDate:"N/A"};const r=apr/100/12;let m=0,interestTotal=0,b=balance;while(b>0&&m<1200){const interest=b*r;if(payment<=interest&&r>0)return{months:"Not reducing",totalInterest:interestTotal,payoffDate:"N/A"};b+=interest;interestTotal+=interest;b-=payment;m++}if(m>=1200)return{months:"100+ years",totalInterest:interestTotal,payoffDate:"N/A"};const d=new Date();d.setMonth(d.getMonth()+m);return{months:m,totalInterest:interestTotal,payoffDate:d.toLocaleDateString("en-GB",{month:"short",year:"numeric"})}}

function renderDashboard(){const income=Number(state.income||0),out=totalExpenses(),paid=paidThisMonth(),remaining=remainingToPay(),left=income-remaining;incomeDisplay.textContent=money(income);outgoingsDisplay.textContent=money(out);paidDisplay.textContent=money(paid);leftDisplay.textContent=money(left);leftDisplay.className=left>=0?"positive":"negative";remainingText.textContent=`Remaining to pay: ${money(remaining)}`;debtTotalText.textContent=`Total debt: ${money(totalDebt())}`;incomeInput.value=state.income}
function renderExpenses(){expensesList.innerHTML="";if(!state.expenses.length){expensesList.innerHTML='<article class="data-card"><div class="data-title">No bills or expenses yet.</div><div class="data-subtitle">Add your first item above.</div></article>';return}state.expenses.forEach(item=>{const card=document.createElement("article");card.className="data-card";card.innerHTML=`<div class="data-card-top"><div><div class="data-title">${item.name}</div><div class="data-subtitle">${item.recurring?"Recurring monthly":"One-off item"}</div></div><label class="checkline"><input class="checkbox" type="checkbox" ${item.paid?"checked":""} data-action="toggle-paid" data-id="${item.id}">Paid</label></div><div class="data-grid"><div class="data-field"><div class="data-label">Amount</div><div class="data-value">${money(item.amount)}</div></div><div class="data-field"><div class="data-label">Remaining</div><div class="data-value">${item.paid?money(0):money(item.amount)}</div></div></div><div class="data-actions"><button class="icon-btn edit" data-action="edit-expense" data-id="${item.id}">Edit</button><button class="icon-btn delete" data-action="delete-expense" data-id="${item.id}">Delete</button></div>`;expensesList.appendChild(card)})}
function renderDebts(){debtsList.innerHTML="";if(!state.debts.length){debtsList.innerHTML='<article class="data-card"><div class="data-title">No debts added.</div><div class="data-subtitle">Add a debt only if you want to track one.</div></article>';return}state.debts.forEach(debt=>{const r=amortiseDebt(debt.balance,debt.payment,debt.apr),card=document.createElement("article");card.className="data-card";card.innerHTML=`<div class="data-card-top"><div><div class="data-title">${debt.name}</div><div class="data-subtitle">APR ${Number(debt.apr||0).toFixed(2)}%</div></div></div><div class="data-grid"><div class="data-field"><div class="data-label">Balance</div><div class="data-value">${money(debt.balance)}</div></div><div class="data-field"><div class="data-label">Monthly Payment</div><div class="data-value">${money(debt.payment)}</div></div><div class="data-field"><div class="data-label">Months Left</div><div class="data-value">${r.months}</div></div><div class="data-field"><div class="data-label">Total Interest</div><div class="data-value">${money(r.totalInterest)}</div></div><div class="data-field"><div class="data-label">Payoff Date</div><div class="data-value">${r.payoffDate}</div></div></div><div class="data-actions"><button class="icon-btn edit" data-action="edit-debt" data-id="${debt.id}">Edit</button><button class="icon-btn delete" data-action="delete-debt" data-id="${debt.id}">Delete</button></div>`;debtsList.appendChild(card)})}
function renderHistory(){historyList.innerHTML="";if(!state.history.length){historyList.innerHTML='<article class="data-card"><div class="data-title">No archived months yet.</div></article>';return}[...state.history].reverse().forEach(item=>{const card=document.createElement("article");card.className="data-card";card.innerHTML=`<div class="data-card-top"><div><div class="data-title">${item.date}</div><div class="data-subtitle">Monthly snapshot</div></div></div><div class="data-grid"><div class="data-field"><div class="data-label">Income</div><div class="data-value">${money(item.income)}</div></div><div class="data-field"><div class="data-label">Expenses</div><div class="data-value">${money(item.totalExpenses)}</div></div><div class="data-field"><div class="data-label">Paid</div><div class="data-value">${money(item.paid)}</div></div><div class="data-field"><div class="data-label">Remaining</div><div class="data-value">${money(item.remaining)}</div></div><div class="data-field"><div class="data-label">Debt</div><div class="data-value">${money(item.totalDebt)}</div></div></div><div class="data-actions"><button class="icon-btn delete" data-action="delete-history" data-id="${item.id}">Delete</button></div>`;historyList.appendChild(card)})}

const expenseChartCanvas=document.getElementById("expenseChart"),debtChartCanvas=document.getElementById("debtChart");
function createOrUpdateCharts(){const expenseLabels=state.expenses.map(x=>x.name),expenseData=state.expenses.map(x=>Number(x.amount||0)),debtLabels=state.debts.map(x=>x.name),debtData=state.debts.map(x=>Number(x.balance||0));if(!expenseChart){expenseChart=new Chart(expenseChartCanvas,{type:"doughnut",data:{labels:expenseLabels,datasets:[{label:"Expenses",data:expenseData}]},options:{responsive:true,maintainAspectRatio:false,resizeDelay:200,animation:false}})}else{expenseChart.data.labels=expenseLabels;expenseChart.data.datasets[0].data=expenseData;expenseChart.update("none")}if(!debtChart){debtChart=new Chart(debtChartCanvas,{type:"bar",data:{labels:debtLabels,datasets:[{label:"Debt Balance",data:debtData}]},options:{responsive:true,maintainAspectRatio:false,resizeDelay:200,animation:false}})}else{debtChart.data.labels=debtLabels;debtChart.data.datasets[0].data=debtData;debtChart.update("none")}}
function scheduleChartRender(){clearTimeout(chartRenderTimer);chartRenderTimer=setTimeout(createOrUpdateCharts,50)}
function render(){if(!unlocked)return;renderDashboard();renderExpenses();renderDebts();renderHistory();scheduleChartRender();saveState()}

incomeInput.addEventListener("input",e=>{state.income=Number(e.target.value||0);render()});
expenseForm.addEventListener("submit",e=>{e.preventDefault();const name=expenseName.value.trim(),amount=Number(expenseAmount.value),recurring=expenseRecurring.checked;if(!name||amount<0)return;state.expenses.push({id:crypto.randomUUID(),name,amount,paid:false,recurring});e.target.reset();expenseRecurring.checked=true;render()});
debtForm.addEventListener("submit",e=>{e.preventDefault();const name=debtName.value.trim(),balance=Number(debtBalance.value),payment=Number(debtPayment.value),apr=Number(debtInterest.value||0);if(!name||balance<0||payment<0||apr<0)return;state.debts.push({id:crypto.randomUUID(),name,balance,payment,apr});e.target.reset();render()});

document.addEventListener("click",e=>{const action=e.target.dataset.action,id=e.target.dataset.id;if(!action||!id)return;if(action==="edit-expense"){const item=state.expenses.find(x=>x.id===id);if(!item)return;const name=prompt("Item name:",item.name);if(name===null)return;const amount=prompt("Amount:",item.amount);if(amount===null)return;const recurring=confirm("Recurring every month? OK = Yes, Cancel = No.");item.name=name.trim()||item.name;item.amount=Number(amount||item.amount);item.recurring=recurring;render()}if(action==="delete-expense"){state.expenses=state.expenses.filter(x=>x.id!==id);render()}if(action==="edit-debt"){const debt=state.debts.find(x=>x.id===id);if(!debt)return;const name=prompt("Debt name:",debt.name);if(name===null)return;const balance=prompt("Balance:",debt.balance);if(balance===null)return;const payment=prompt("Monthly payment:",debt.payment);if(payment===null)return;const apr=prompt("APR %:",debt.apr);if(apr===null)return;debt.name=name.trim()||debt.name;debt.balance=Number(balance||debt.balance);debt.payment=Number(payment||debt.payment);debt.apr=Number(apr||0);render()}if(action==="delete-debt"){state.debts=state.debts.filter(x=>x.id!==id);render()}if(action==="delete-history"){state.history=state.history.filter(x=>x.id!==id);render()}});
document.addEventListener("change",e=>{const action=e.target.dataset.action,id=e.target.dataset.id;if(action==="toggle-paid"){const item=state.expenses.find(x=>x.id===id);if(item){item.paid=e.target.checked;render()}}});
markAllPaidBtn.addEventListener("click",()=>{state.expenses.forEach(x=>x.paid=true);render()});
markAllUnpaidBtn.addEventListener("click",()=>{state.expenses.forEach(x=>x.paid=false);render()});
resetMonthBtn.addEventListener("click",()=>{if(!confirm("Reset all paid ticks to unpaid?"))return;state.expenses.forEach(x=>x.paid=false);render()});
archiveMonthBtn.addEventListener("click",()=>{state.history.push({id:crypto.randomUUID(),date:new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}),income:state.income,totalExpenses:totalExpenses(),paid:paidThisMonth(),remaining:remainingToPay(),totalDebt:totalDebt()});state.expenses=state.expenses.filter(x=>x.recurring).map(x=>({...x,paid:false}));render()});
factoryResetBtn.addEventListener("click",()=>{if(!confirm("This will delete all saved finance data. Continue?"))return;state=structuredClone(blankState);render()});
loadSampleBtn.addEventListener("click",()=>{if(!confirm("Load sample data? This will replace current data."))return;state=structuredClone(sampleState);render()});
exportBtn.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`finance-monthly-money-tracker-backup-v${APP_VERSION}.json`;link.click();URL.revokeObjectURL(url)});
importInput.addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=migrateState(JSON.parse(reader.result));render()}catch{alert("Import failed. Please check the backup file.")}};reader.readAsText(file)});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.classList.remove("hidden")});
installBtn.addEventListener("click",async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.classList.add("hidden")});
window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;installBtn.classList.add("hidden")});
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(console.error);
saveState();showAuthMode();
